# Generated by Django 4.2 on 2023-04-09 03:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Personality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extraversion', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('smokeOrDrink', models.CharField(choices=[('no', 'No'), ('smoke', 'Smoke'), ('drink', 'Drink'), ('both', 'Both')], max_length=20)),
                ('cleanliness', models.CharField(choices=[('neat', 'Neat'), ('neutral', 'Neutral'), ('messy', 'Messy')], max_length=20)),
                ('social', models.CharField(choices=[('friendly', 'Friendly and outgoing'), ('moderate', 'Moderately Social'), ('quiet', 'Quiet and Reserved')], max_length=20)),
                ('genderPreference', models.CharField(choices=[('friendly', 'Friendly and outgoing'), ('moderate', 'Moderately Social'), ('quiet', 'Quiet and Reserved')], max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=40)),
                ('location', models.CharField(max_length=40)),
                ('season', models.CharField(max_length=40)),
                ('budget', models.CharField(max_length=40)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profilePic', models.ImageField(upload_to='photos/')),
                ('firstName', models.CharField(max_length=30)),
                ('lastName', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('college', models.CharField(max_length=60)),
                ('major', models.CharField(max_length=40)),
                ('pronoun', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
